# Generated by Django 2.2.4 on 2019-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=200)),
                ('rest_add', models.CharField(max_length=1000)),
                ('rest_lat', models.FloatField()),
                ('rest_lon', models.FloatField()),
                ('rest_desc', models.TextField()),
                ('rest_rate', models.FloatField()),
                ('rest_num_review', models.IntegerField()),
                ('rest_avgcost', models.FloatField()),
            ],
        ),
    ]
